### ISSUE TITLE
Automated docker image build?

### ISSUE THREAD

**Issue by LM1LC3N7** [jippi/docker-pixelfed#33]
Hi @jippi 

Thanks a lot for your hard work on PixelFed, I really appreciate.
I am wondering if you will setup automated github package build based on pixelfed released?

As for now, there is one version late if I am not wrong, but if this involves a manual work, it might be not the best for you to keep up.

Anyway, this is more like a thanks and "idea" issue.

**Comment by jippi** [comment]
Hey; there are currently no "automated" (as in on "tag"/"release") but Dansup and I both have access to cut the releases, and from there on, its fully automated.

This repo and container registry should be up to date with latest releases though, I'm running my site from this repo and its current. See [Docker and Pixelfed versions](https://jippi.github.io/docker-pixelfed/customize/tags/) documentation for more information :)

**Comment by LM1LC3N7** [comment]
Thanks a lot for your answer! I was using the old repo and image jippi fork. Now I have updates, thanks :)
